### ISSUE TITLE
Amounts are not following number format rules

### ISSUE THREAD

**Issue by ruichaparro** [WJDDesigns/Ultra-Vehicle-Card#108]
Hi,

First of all, great job!

I'm on 1.6.1. There is an issue with the way numbers are displaying. It is not following the number format rules.

My default uses "," as the decimal separator. This causes numbers to be incorrectly displayed. For example, my mileage is 115621.1 km. If I go the user settings and set the Number Format as "1,234,567.89" it works fine, and displays "115,621 km". But if I keep my language default format, which is "1.234.567,89", it displays "116.1 km"

I have a feeling that this was working fine in previous versions (before 1.6.0), but I can't be sure. 

Regards,
Rui

**Comment by WJDDesigns** [comment]
Please download the latest and restart Home Assistant then clear cache. This has been fixed in previous versions.

Make sure your language is set in the settings and then choose the number format you would like to display per entity.

![edb11252d5766a2f7c08a714c97f3fe902d3efd9](https://github.com/user-attachments/assets/25c9e2d9-c0bc-47a2-8ea3-a0d96a1e5c4d)

**Comment by WJDDesigns** [comment]
No problem, glad it is fixed! I will go ahead and close this issue out.
