### ISSUE TITLE
Icon Grid Configuration -> Custom Card instead Icon?

### ISSUE THREAD

**Issue by clipse2004** [WJDDesigns/Ultra-Vehicle-Card#139]
Hi,
good job first! :) 
But I have a question, in the Icon Grid Configuration, would it be possible to insert a card instead of the individual entities?
Because I've made something out of the "actual" car app. That would be awesome!

And one more question about animation, where do I find this tab on the map? I don't see it anywhere.

Big thanks

**Comment by WJDDesigns** [comment]
This is not built to pull in a card inside of the card. This is built to be the ultimate vehicle card (see the name, I took us awhile to come up with it ;) ) We made this universal so it can pull in any entity and won't be pulling in actual cards in to a card since that sounds like some kind of scary cardception. 

As far as the animations are concerned, just make sure an entity that either has the state of on/off inside Engine On Entity or Charging Animation and it will show the animation when that entity is on.
