### ISSUE TITLE
Location formatting breaks correctly cased-names

### ISSUE THREAD

**Issue by chobbs42** [WJDDesigns/Ultra-Vehicle-Card#43]
Your _formatLocationState function takes a location name and re-formats it to capitalize each word. It seems like it shouldn't mess with the name chosen by the user when the Zone was created. For example, I've created the following Zone:
![image](https://github.com/user-attachments/assets/402b32e7-99e0-4c0c-b6db-479645459d6f)

However, your code renders it as:
![image](https://github.com/user-attachments/assets/9d7a7e35-2d29-4686-aa02-0d962569df10)

I don't think it is expected behavior to have a card reformatting the zone name in this fashion.

**Comment by WJDDesigns** [comment]
Yeah I did that because for example when my car is Home it was showing up as home even though the zone is Home. I have learned that is an issue with device tracker more so and to leave it alone or use a template. https://community.home-assistant.io/t/device-tracker-zone-name-capitalization/22138 - I have updated code to fix this and will be in the next update cycle.

**Comment by chobbs42** [comment]
Dr. Pepper sent :)

**Comment by WJDDesigns** [comment]
Hey, I appreciate you!
