### ISSUE TITLE
Switching to Lovelace code-view freezes editor

### ISSUE THREAD

**Issue by weavel** [WJDDesigns/Ultra-Vehicle-Card#6]
I wanted to integrate this card in my front-end, which is made up by some vertical stacks. When trying to switch to the manual code-edit, the page freezes and after some time the browsers asks to stop the running of scripts. I've observed this behaviour in both Microsoft Edge and Firefox on a Macbook runnning Sonoma 14.5 and also on Safari on my iPhone.

Debugging the window in Firefox results in the following error (in Dutch):

> Fout tijdens het ophalen van een originele bron: request failed with status 404
> Bron-URL: https://homeassistant.home.weavel.nl/unknown/node_modules/@codemirror/language/dist/index.js

When I remove the card from the dashboard the editor no longer freezes. This does not happen when editing another stack where the card is not present. Let me know if you need more! Thank you so much for creating this card!

**Comment by WJDDesigns** [comment]
I figured out the issue with this but for right now might not be able to fix it completely although I did get the wait time down to switching. The problem is allowing the user to upload their own image to the card which saves it as a base64 long character url which then adds on to the full code of the card. If you link directly to an image on the web it doesn't have this issue. I did not see these cards affecting other cards though and my other cards can easily be switched to code editor without freezing or delays.

**Comment by sanchosk** [comment]
Same experience here - replacing the uploaded image with URL fixes the problem.

**Comment by weavel** [comment]
Thanks for the response. I don't like pinging external sources from the internet for various reason, primarily being dependent on someone elses hosting, so I uploaded the picture file to the ```config/www``` folder in the Home Assistant config, as documented [per here](https://www.home-assistant.io/integrations/http#hosting-files) and referenced this file in the cards config.
