### ISSUE TITLE
Possible Bug: No ability to choose trigger entity

### ISSUE THREAD

**Issue by CaptInsano** [WJDDesigns/Ultra-Vehicle-Card#62]
I am trying to set up an icon to allow me toggle my charger's locked status using a script (As toggle does not work on locks).

![image](https://github.com/user-attachments/assets/b96b649e-4cef-439b-b42a-a1741085ef3d)

I want the status icons to relate to the entity I have chosen (Wallbox MQTT Lock) but I was to trigger a script when the icon is clicked.
When I choose "Trigger" as the interaction there is no option to choose which script/automation I wish to trigger.

I have restarted HomeAssistant, did an "Empty Cache and Hard Reload" in Chrome, used different browsers but there is no option to choose which script I wish to trigger?

Any advise on this?

Thanks for your work on this card

**Comment by WJDDesigns** [comment]
1. In the card configuration, add the automation or script you want to trigger to the icon grid:

- Under "Icon Grid Entities", click "Add Entity".
- Search for and select your automation or script.

2. Configure the interaction for the newly added entity:

- Find the entity you just added in the list.
- In the "Interaction" dropdown next to it, select "Trigger".

3. Save the card configuration.

4. In the frontend, the icon for your automation or script should now appear in the card's icon grid.

5. Clicking this icon will trigger the automation or script once, without toggling it on or off.

Important notes:

- For automations, this will run the automation once, regardless of its current state.
- For scripts, this will run the script once.
- For automations, it calls the automation.trigger service.
- For scripts, it calls the script.turn_on service.
- The icon state (active/inactive) is based on the entity's current state, but clicking it will always trigger the entity, not toggle it.

If you're still experiencing issues:

- Ensure that the entity you've selected is indeed an automation or script.
- Check that you have the necessary permissions to trigger the automation or script.
- Try reloading the page after saving the configuration to ensure all changes are applied.

Remember, "Trigger" is different from "Toggle". It's designed to run the automation or script once, rather than switch it on or off.

If you're still having trouble, please provide more details about the specific automation or script you're trying to trigger, and any error messages you might be seeing.

Use Cases:

1. Remote Start: A user might have an automation or script set up to remotely start their vehicle. They could add this as an icon on your card with the "Trigger" interaction, allowing them to start their car with a single tap.
2. Charge Now: For electric vehicles, a user might have a script that overrides their usual charging schedule to start charging immediately. This could be useful if they need to leave earlier than expected and want to ensure their car is charged.
3. Defrost/Heat: In cold climates, users might have an automation to start the car's defrost or heating system. Having this as a triggerable icon on your card would allow them to easily prepare their car before leaving.

**Comment by CaptInsano** [comment]
Thanks for this,

I had thought it was possible to have icon states based on a different entity than the script entity:

ie: The icon reacts to state of charger lock (lock.wallbox_mqtt) but clicking the icon triggers the script.togglewallboxlock.

I now understand that is not possible!

Thanks a million again

**Comment by WJDDesigns** [comment]
We thought about this but we also thought that approach might confuse general users.We might explore this down the road if there is a need.

**Comment by maddox** [comment]
It would be nice, even if we have to drop to yaml to do it. Mostly because triggering an action (service call) is a normal option for items in the dashboard.
